[package]
name = "chainder"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
fxhash = "0.2"
memchr = "2.7"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
flate2 = "1.0"

[profile.release]
lto = true
